language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bencotton/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bencotton/docker-react npm run test